server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000

spring:
  application:
    name: high-concurrency-order-processing
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_orders
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  security:
    jwt:
      secret-key: ${JWT_SECRET:default_super_long_secret_key_for_tests_please_change_in_prod_ABCDEFGHIJKLMNOPQRSTUVWXYZ}
      expiration: ${JWT_EXPIRATION:3600000}
      

  cache:
    type: simple

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.ecommerce.orderprocessing: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/order-processing.log

# Application specific configuration
app:
  payment:
    gateway:
      url: ${PAYMENT_GATEWAY_URL:https://api.stripe.com/v1}
      api-key: ${PAYMENT_GATEWAY_API_KEY}
      timeout: 5000
  
  inventory:
    service:
      url: ${INVENTORY_SERVICE_URL:http://localhost:8081}
      timeout: 3000
  
  virtual-threads:
    enabled: true
    executor:
      core-pool-size: 10
      max-pool-size: 100

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true